-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Usr CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Topic CASCADE;
DROP TABLE IF EXISTS Reply CASCADE;
DROP TABLE IF EXISTS UsrSeenTopic CASCADE;
